name: Publish Extension
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install vsce locally
        run: npm install --save-dev @vscode/vsce

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Update package version if needed
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [ "$CURRENT_VERSION" != "$TAG_VERSION" ]; then
            npm version $TAG_VERSION --no-git-tag-version
          else
            echo "Package version already matches tag version: $TAG_VERSION"
          fi

      - name: Build extension
        run: npm run package

      - name: Publish extension
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
